### ISSUE TITLE
HTTP Error

### ISSUE THREAD

**Issue by batizisanya** [Bioruebe/CardAvailability#1]
Hi, I need a litle help. I get http error all times when I try to run. I tried to change all http to https, but the same happen.
![image](https://user-images.githubusercontent.com/16525148/41994073-960e03ce-7a4d-11e8-8ec2-3c80d9d2e8c7.png)

**Comment by Bioruebe** [comment]
Sorry, I forgot to upload the updated version. This one is broken for quite some time now.

Check the [releases page](https://github.com/Bioruebe/CardAvailability/releases) for the new version :)
